version: '3'

services:
  server:
    build: .
    container_name: psik_server
    command: npx nodemon src/server/index.ts
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgres://username:password@postgres/psik
    ports:
      - "3000:3000"
    volumes:
      - .:/application
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: psik_db
    volumes:
      - ./.devdb/pgsql:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=psik
    ports:
      - "5455:5432"